app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'

urlpatterns=[
    path('app1_fun/',app1_fun,name='app1_fun')
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'

urlpatterns=[
    path('app2_fun/',app2_fun,name='app2_fun'),
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
import app2
from app1.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('app1_string/',app1_string,name='app1_string')
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def app1_fun(request):
    return render(request, 'app1.html')
    
def app1_string(request):
    return HttpResponse('<h1>this is app1 string content')

app2/views.py
from django.shortcuts import render

# Create your views here.
def app2_fun(request):
    return render(request, 'app2.html')

templates/app1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>this is app1 html content</h1>
    <h2>direction links</h2>
    <h6><a href="{% url 'app2:app2_fun' %}">go to app2 html page</a></h6>
    <h6><a href="{% url 'app1_string' %}">go to app app_string</a></h6>
</body>
</html>

templates/app2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>this is app2 html file content</h1>
    <h6><a href="{% url 'app1:app1_fun' %}">go to app1 html page</a></h6>
    <h6><a href="{% url 'app1_string' %}">go to app1_string</a></h6>
</body>
</html>l